### PR TITLE
Fix for issue #3

### PR DESCRIPTION
**Pull request by eagl3s1ght**
running composer install overwrites app/design/frontend/base/default/template/ when magento-deploy-strategy is set to symlink, so we need to be more precise with the mapping as other files are in the overwritten folder.

### CODE REVIEW

**Comment by TekniskSupport** [comment]
Hi, 

Thank you for your contribution!
I had a few comments about utilizing the logger instead of directly calling mage::log

Otherwise great work, thanks!

**Comment by eagl3s1ght** [comment]
Oh sorry, those commits were not meant to be included in the merge

**Comment by TekniskSupport** [comment]
Hi,

Ok,no worries, i cherry picked the fixes.

Kind Regards Iesus

**Comment by eagl3s1ght** [comment]
I think you may have cherrypicked the wrong commit. Should be https://github.com/sveawebpay/magento1-checkout/pull/4/commits/7c21e68176dba5cc620a7708ff3846610ba9ff0a

**Comment by TekniskSupport** [comment]
Hi again 

I cherrypicked two commits

the ones with these commit messages:
```
   Override $nosave, this file is a mystery which crashes randomly when method names are empty, without describing errors.
```
and:

    Fix for issue #3
    running composer install overwrites app/design/frontend/base/default/template/ when magento-deploy-strategy is set to symlink, so we need to be more precise with the mapping as other files are in the overwritten folder.


commit https://github.com/sveawebpay/magento1-checkout/commit/7c21e68176dba5cc620a7708ff3846610ba9ff0a === 5cfc574d08c4ccb63da7220a5262dd9ddcc52614

**Comment by eagl3s1ght** [comment]
Ok, I don't know if https://github.com/sveawebpay/magento1-checkout/pull/4/commits/1ea6ecc3826e3f960836ae01f1c3dca0a97575ec is ready for production, it was a commit for local testing. We're having issues with the module breaking when table rate shipping is enabled on our site.

Sorry for any issues created, I'm new to github pull requests so I did not know pushing to my fork master would also add it to the pull request.

**Comment by TekniskSupport** [comment]
Ok, i'll revert the commit then, no problem

**Pull request closed without merging**
